powerin <- read.table("household_power_consumption.txt",header=T,sep=";",stringsAsFactors = F)
datain <- filter(powerin,Date %in% c("1/2/2007","2/2/2007"))

datain$dateTime <- paste(datain$Date,datain$Time,sep=" ")
datain$dateTime <- strptime(datain$dateTime,"%d/%m/%Y %H:%M:%S")
datain$Global_active_power <- as.numeric(datain$Sub_metering_1)
datain$Global_active_power <- as.numeric(datain$Sub_metering_2)
datain$Global_active_power <- as.numeric(datain$Sub_metering_3)

png("plot3.png",height=480,width=480)
par(mfrow=c(1,1))
plot(datain$dateTime,datain$Sub_metering_1,xlab = "",ylab="Energy Sub Metering",type = "l",col="black")
lines(datain$dateTime,datain$Sub_metering_2,type="l",col="red")
lines(datain$dateTime,datain$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","green"))
dev.off()